<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Validation</RootNamespace>
    <UseAppHost>false</UseAppHost>
    <DefaultItemExcludes>$(DefaultItemExcludes);tests/**;samples/**;Api/**;Api.Tests/**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="OpenAI" Version="2.13.0" />
  </ItemGroup>
</Project>
