<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>AutomatedMigration.Api</RootNamespace>
    <AssemblyName>AutomatedMigration.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutomatedMigration\AutomatedMigration.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="AutomatedMigration.Api.Tests" />
  </ItemGroup>

</Project>
